### ISSUE TITLE
.vimx

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-web#18]
# Goal

Implement a VIMX file which can be consumed by the VIM webgl viewer to render the geometry in a manner which improves the time to first presentation.

# Phase 1

- [x] VIMX proof-of-concept
  - [x] Give it an extension: .vimx
  - [x] Add new attribute for per-instance world space axis-aligned bounding boxes (AABBs)
  - [x] Update the index attribute with a singular world space AABB for the whole model (for camera framing purposes).
  - [ ] Define instance transforms to the top-level
  - [ ] Modify chunk layout to use unified vertex and index buffer (resume usage of Mesh and Submesh)

- [ ] VIMX vim-format repository integration
  - [x] Refactor Vim.BFast implementation to improve ergonomics
  - [x] In the src/cs/g3d folder:
    - [x] Add the C# project Vim.G3d.Next which contains the refactored code for attributes and their code generation
    - [x] Add the C# project Vim.G3d.Next.Tests to test the implementation
  - [ ] In the src/cs/vim folder:
    - [x] Add the C# project Vim.Format.Vimx which is responsible for reading and writing VIMX files 
      - [x] The VIMX header should designate itself as a "vimx=0.1.0" (to make a clear distinction between a VIM and a VIMX)
      - [x] The remainder of the file header should be similar to the original VIM format.
      - [x] Implement a bucketing scheme which enables the batch download of meshes that are members of the same category (or some other bucketing heuristic) to reduce the number of queries (and to improve the loading time).
    - [ ] Adapt Vim.Format with new implementations of bfast/g3d.
      - [ ] Replace old Vim.BFast with new implementation
        - [x] Update vim.format repo with new Vim.BFast implementation
        - [ ] Update vimaec repo with new Vim.BFast implementation
          - [ ] Ensure Vim.Migration project works correctly
      - [ ] Replace old Vim.G3d with new implementation
      - [ ] Update the C# project Vim.Format.Tests to test the implementation of VIMX
        - [ ] In the data folder, add a few .vimx files to test the implementation.

- [x] VIM to VIMX conversion via the VIM Tool
  ```ps
  .\Vim.VimTool.exe convert-vimx
    --input "path/to/file.vim"      # input VIM file
    --output "path/to/file.vimx"    # output VIMX file
    --log "path/to/file.log"        # log filepath
  ```

- [x] Refactor viewer selection to enable selecting objects in the VIMx
  - A VIM file with missing entities may have selection disabled
  - VIMX always has selection enabled (because it can base the element selection on the "group" (aka element index))

- [ ] VIMX URL integration into PowerBI Reports
  - [x] Distinguish between a VIM file and a VIMx file and cache the result, presumably by investigating the VIM header
  - [x] Normalize PBI loading pipeline between VIM and VIMx
  - [x] Resolve "initially loaded set" caching
  - [x] Re-enable all features for VIMx in PowerBI + handle special cases (widget toggles)
    - [x] Selection outline
    - [x] Coloring
    - [x] Isolation
    - [x] Back-port refactoring with normal VIM
  - [ ] Test with large models
    - [ ] Test Hexagon big model as .vimx in PBI
    - [ ] Test TG Gallagher big model as .vimx in PBI
    - [ ] Test Whiteleys as .vimx in PBI
    - [ ] Test NBK as .vimx in PBI
  - [ ] Manual tests (validate that performance is adequate)
  
- [ ] VIMX integration into Vim.Glue
  - Also converts the VIM to a VIMX and uploads it to the storage account

- [ ] VIMX integration into VIM Cloud
  - During the azure batch conversion process, if the VIM file's corresponding VIMX file does not already exist, convert the input VIM file to a VIMX and upload it to the org's storage account.
    - This VIMX file should remain hidden from the user and should not count against their storage quota
    - Upon deletion of the original VIM file, the dependent VIMX file is also deleted.
  - Use the VIMX's URL in the PowerBI report.

# Phase 2

- [ ] Complete VIMX transition:
  - [x] VIM WebGL Component
  - [ ] VIM Revit Exporter
  - [ ] VIM Desktop App
    - Implies updating the C++ format...
  - [ ] VIM 3dsMax Importer
  - [ ] VIM Tool (vim to sql)
  - [ ] VIM Cloud as natively supported format
